#! /bin/bash

# Set GCP projection
gcloud config configurations activate brett-east

npm run build
echo "===============: Deploying ${CLOUDSDK_CORE_PROJECT} app to gcloud"

gcloud app deploy -q app.yaml --ignore-file .gcloudignore
